'use client';
import {useMemo,useState} from 'react';
import {allTeamNeeds,evaluateTrade,optimizeLineup,playerValue,powerRankings,tradeRecommendations,tradeValue,warRoomScore} from '@/lib/insights';
const tabs=['Dashboard','My Team','War Room','Team Needs','Trade Center','Player Values','Free Agents','League','News'];
const scoreClass=(n:number)=>n>=84?'scoreA':n>=68?'scoreB':'scoreC';
export default function DashboardTabs({payload,news,mine,teams,fas}:any){
 const [tab,setTab]=useState('Dashboard'); const all=useMemo(()=>[...teams.flatMap((t:any)=>t.players||[]),...fas],[teams,fas]);
 const needs=useMemo(()=>allTeamNeeds(teams,all),[teams,all]); const power=useMemo(()=>powerRankings(teams,all),[teams,all]); const lineup=useMemo(()=>mine?optimizeLineup(mine.players||[],all):{starters:[],bench:[]},[mine,all]); const ideas=useMemo(()=>tradeRecommendations(mine,teams,all),[mine,teams,all]);
 return <><nav className="tabBar">{tabs.map(t=><button key={t} className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='Dashboard'&&<Dashboard teams={teams} fas={fas} mine={mine} needs={needs} power={power} ideas={ideas}/>} 
 {tab==='My Team'&&<MyTeam mine={mine} lineup={lineup} all={all}/>} 
 {tab==='War Room'&&<WarRoom teams={teams} fas={fas} all={all}/>} 
 {tab==='Team Needs'&&<TeamNeeds needs={needs}/>} 
 {tab==='Trade Center'&&<TradeCenter teams={teams} mine={mine} all={all} ideas={ideas}/>} 
 {tab==='Player Values'&&<PlayerValues all={all} teams={teams}/>} 
 {tab==='Free Agents'&&<FreeAgents fas={fas} mine={mine} teams={teams} all={all}/>} 
 {tab==='League'&&<League power={power} teams={teams}/>} 
 {tab==='News'&&<News news={news}/>}</>
}
function Dashboard({teams,fas,mine,needs,power,ideas}:any){const myNeed=needs.find((x:any)=>x.team===mine?.name);return <><section className="grid"><Metric label="Teams Connected" value={teams.length||'—'}/><Metric label="Free Agents Analyzed" value={fas.length||'—'}/><Metric label="Nixflix Players" value={mine?.players?.length||'—'}/><Metric label="Biggest Nixflix Need" value={myNeed?.top?.position||'—'} sub={myNeed?.top?`${myNeed.top.label} • ${myNeed.top.score}/100`:'Awaiting live data'}/></section><section className="grid"><div className="card s7"><h2>Front Office Priorities</h2>{myNeed?.needs?.slice(0,4).map((n:any)=><div className="needRow" key={n.position}><div><b>{n.position}</b> <span className={`pill ${scoreClass(n.score)}`}>{n.label}</span><div className="tiny muted">{n.why}</div></div><b>{n.score}/100</b></div>)||<Empty text="Connect Yahoo to calculate current priorities."/>}</div><div className="card s5"><h2>Best Trade Paths</h2>{ideas.slice(0,5).map((x:any)=><div className="newsItem" key={x.partner+x.target.name}><b>{x.target.name}</b> from {x.partner}<div className="tiny">Offer concept: {x.offer.name} • HQ {x.score}/100</div><div className="tiny muted">{x.reason}</div></div>)}{!ideas.length&&<Empty text="Trade recommendations activate with live rosters."/>}</div></section><section className="grid"><div className="card s12"><h2>League Power Snapshot</h2><Table headers={['Rank','Team','HQ Strength','Top Asset']} rows={power.map((x:any)=>[`#${x.rank}`,<b key="t">{x.team}</b>,x.score,x.top])}/></div></section></>}
function MyTeam({mine,lineup,all}:any){return <section className="grid"><div className="card s7"><h2>Nixflix Optimized Lineup</h2><Table headers={['Slot','Player','Pos','HQ Value']} rows={(lineup.starters||[]).map((x:any)=>[x.slot,<b key="p">{x.player?.name||'—'}</b>,x.player?.position||'—',x.value||'—'])}/></div><div className="card s5"><h2>Bench / Roster Value</h2>{(lineup.bench||[]).map((x:any)=><div className="needRow" key={x.name}><span><b>{x.name}</b> <span className="pill">{x.position}</span></span><b>{playerValue(x,all)}</b></div>)}{!mine&&<Empty text="Nixflix roster appears after Yahoo is connected."/>}</div></section>}
function WarRoom({teams,fas,all}:any){const [teamName,setTeamName]=useState('Nixflix and Chill');const [q,setQ]=useState('');const [selected,setSelected]=useState<any>(null);const team=teams.find((t:any)=>t.name===teamName);const results=q.length>=2?all.filter((p:any)=>p.name.toLowerCase().includes(q.toLowerCase())).slice(0,12):[];const r=selected&&team?warRoomScore(selected,team,all):null;return <section className="grid"><div className="card s5"><h2>Player Acquisition War Room</h2><label>Evaluate for team</label><select value={teamName} onChange={e=>setTeamName(e.target.value)}>{teams.map((t:any)=><option key={t.name}>{t.name}</option>)}</select><label>Search any rostered player or free agent</label><input value={q} onChange={e=>{setQ(e.target.value);setSelected(null)}} placeholder="Type at least 2 letters…"/>{results.map((x:any)=><button className="searchResult" key={x.name} onClick={()=>{setSelected(x);setQ(x.name)}}><b>{x.name}</b><span>{x.position} • {ownerOf(x,teams)}</span></button>)}<p className="tiny muted">Search returns a limited matching set rather than exposing complete opposing rosters.</p></div><div className="card s7">{r?<><div className="scoreHero"><div><div className="muted">WAR ROOM SCORE</div><div className={scoreClass(r.score)}>{r.score}<small>/100</small></div></div><span className="gradeBig">{r.grade}</span></div><h2>{selected.name} → {teamName}</h2><div className="scoreGrid"><Score label="Player Value" n={r.value}/><Score label="Position Need" n={r.need}/><Score label="Net Upgrade" n={r.net}/><Score label="Drop Value" n={r.dropValue}/></div><h3>Why target him</h3><p>{r.why}</p><h3>Recommended drop: {r.drop?.name||'—'}</h3><p>{r.dropWhy}</p></>:<Empty text="Choose a team and search for a player. HQ will score the acquisition, explain the fit, and identify the best drop."/>}</div></section>}
function TeamNeeds({needs}:any){return <section className="grid"><div className="card s12"><div className="sectionTitle"><h2>Every Team's Biggest Positional Needs</h2><span className="pill">0–100 urgency</span></div><div className="needsGrid">{needs.map((t:any)=><div className="miniCard" key={t.team}><h3>{t.team}</h3>{t.needs.map((n:any)=><div className="needBlock" key={n.position}><div className="needHead"><b>{n.position}</b><span className={scoreClass(n.score)}>{n.score} • {n.label}</span></div><div className="bar"><i style={{width:`${n.score}%`}}/></div><div className="tiny muted">{n.why}</div></div>)}</div>)}</div>{!needs.length&&<Empty text="Needs will calculate for all 10 teams when Yahoo data is live."/>}</div></section>}
function TradeCenter({teams,mine,all,ideas}:any){const [a,setA]=useState('Nixflix and Chill'),[b,setB]=useState(teams.find((x:any)=>x.name!=='Nixflix and Chill')?.name||'');const [aq,setAq]=useState(''),[bq,setBq]=useState('');const [giveA,setGiveA]=useState<any[]>([]),[giveB,setGiveB]=useState<any[]>([]);const ta=teams.find((x:any)=>x.name===a),tb=teams.find((x:any)=>x.name===b);const ev=ta&&tb&&(giveA.length||giveB.length)?evaluateTrade(ta,tb,giveA,giveB,all):null;return <><section className="grid"><div className="card s12"><div className="sectionTitle"><h2>Trade Evaluator</h2><span className="pill">Fantasy Fools custom values</span></div><div className="tradeGrid"><TradeSide label="Team A" team={ta} teams={teams} value={a} setValue={setA} q={aq} setQ={setAq} selected={giveA} setSelected={setGiveA} all={all}/><div className="tradeVs">⇄</div><TradeSide label="Team B" team={tb} teams={teams} value={b} setValue={setB} q={bq} setQ={setBq} selected={giveB} setSelected={setGiveB} all={all}/></div>{ev&&<div className="evalBox"><div className="scoreHero"><div><div className="muted">TRADE SCORE</div><div className={scoreClass(ev.score)}>{ev.score}<small>/100</small></div></div><span className="gradeBig">{ev.verdict}</span></div><div className="scoreGrid"><Score label={`${a} receives`} n={ev.aIn}/><Score label={`${b} receives`} n={ev.bIn}/><Score label="Fairness" n={ev.fairness}/><Score label="Nixflix/Team A Impact" n={ev.aNet}/></div><p><b>{a}:</b> {ev.whyA}</p><p><b>{b}:</b> {ev.whyB}</p></div>}</div></section><section className="grid"><div className="card s12"><h2>Recommended Trade Targets & Partners</h2><Table headers={['HQ','Partner','Target','Target Value','Offer Concept','Offer Value','Why']} rows={ideas.map((x:any)=>[<b className={scoreClass(x.score)} key="s">{x.score}</b>,x.partner,<b key="t">{x.target.name}</b>,tradeValue(x.target,all),x.offer.name,tradeValue(x.offer,all),x.reason])}/>{!ideas.length&&<Empty text="Recommendations activate once all league rosters are available."/>}</div></section></>}
function TradeSide({label,team,teams,value,setValue,q,setQ,selected,setSelected,all}:any){const results=q.length>=2?(team?.players||[]).filter((p:any)=>p.name.toLowerCase().includes(q.toLowerCase())).slice(0,8):[];return <div><label>{label}</label><select value={value} onChange={e=>{setValue(e.target.value);setSelected([]);setQ('')}}>{teams.map((t:any)=><option key={t.name}>{t.name}</option>)}</select><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search this team's players…"/>{results.map((p:any)=><button className="searchResult" key={p.name} onClick={()=>{if(!selected.some((x:any)=>x.name===p.name))setSelected([...selected,p]);setQ('')}}><b>{p.name}</b><span>{p.position} • value {tradeValue(p,all)}</span></button>)}<div className="chips">{selected.map((p:any)=><button className="chip" key={p.name} onClick={()=>setSelected(selected.filter((x:any)=>x.name!==p.name))}>{p.name} <b>{tradeValue(p,all)}</b> ×</button>)}</div></div>}
function PlayerValues({all,teams}:any){const [q,setQ]=useState('');const [pos,setPos]=useState('ALL');const rows=all.filter((p:any)=>(pos==='ALL'||p.position===pos)&&(!q||p.name.toLowerCase().includes(q.toLowerCase()))).sort((a:any,b:any)=>tradeValue(b,all)-tradeValue(a,all)).slice(0,50);return <section className="grid"><div className="card s12"><div className="sectionTitle"><h2>Fantasy Fools Player Values</h2><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player…"/><select value={pos} onChange={e=>setPos(e.target.value)}>{['ALL','QB','RB','WR','TE','K','DEF'].map(x=><option key={x}>{x}</option>)}</select></div></div><Table headers={['Player','Pos','NFL','Owner','Fantasy Pts','HQ Value','Trade Value']} rows={rows.map((p:any)=>[<b key="p">{p.name}</b>,p.position||'—',p.team||'—',ownerOf(p,teams),Number(p.points||0).toFixed(1),playerValue(p,all),<b key="v">{tradeValue(p,all)}</b>])}/></div></section>}
function FreeAgents({fas,mine,teams,all}:any){const [teamName,setTeamName]=useState('Nixflix and Chill');const team=teams.find((t:any)=>t.name===teamName);const rows=team?fas.map((p:any)=>({p,r:warRoomScore(p,team,all)})).sort((a:any,b:any)=>b.r.score-a.r.score).slice(0,60):[];return <section className="grid"><div className="card s12"><div className="sectionTitle"><h2>Free-Agent Fit Board</h2><select value={teamName} onChange={e=>setTeamName(e.target.value)}>{teams.map((t:any)=><option key={t.name}>{t.name}</option>)}</select></div><Table headers={['Player','Pos','War Room','Player Value','Best Drop','Net','Why']} rows={rows.map(({p,r}:any)=>[<b key="p">{p.name}</b>,p.position,<b className={scoreClass(r.score)} key="s">{r.score} {r.grade}</b>,r.value,r.drop?.name||'—',r.net,r.why])}/></div></section>}
function League({power,teams}:any){return <section className="grid"><div className="card s12"><h2>League Power Rankings</h2><Table headers={['Rank','Team','HQ Strength','Top Asset']} rows={power.map((x:any)=>[`#${x.rank}`,<b key="t">{x.team}</b>,x.score,x.top])}/><p className="tiny muted">Opponent rosters are processed for analysis, but the HQ does not expose complete opposing rosters as a bulk list.</p></div></section>}
function News({news}:any){return <section className="grid"><div className="card s12"><h2>Meaningful NFL News</h2>{news.map((n:any)=><div className="newsItem" key={n.external_id}><b>{n.title}</b><div className="tiny muted">{n.source} • impact {n.impact_score}</div><div className="tiny">{(n.players||[]).join(', ')}</div></div>)}{!news.length&&<Empty text="News feed is ready for injury, depth-chart, transaction and role-change signals."/>}</div></section>}
function Metric({label,value,sub}:any){return <div className="card s3"><div className="muted">{label}</div><div className="metric">{value}</div>{sub&&<div className="tiny">{sub}</div>}</div>}
function Score({label,n}:any){return <div className="scoreTile"><span>{label}</span><b>{n>=0&&label.includes('Net')?'+':''}{n}</b></div>}
function Empty({text}:any){return <p className="muted empty">{text}</p>}
function Table({headers,rows=[]}:any){return <div className="wrap"><table><thead><tr>{headers.map((h:string)=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i}>{r.map((c:any,j:number)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function ownerOf(p:any,teams:any[]){return teams.find(t=>(t.players||[]).some((x:any)=>x.name===p.name))?.name||'FA'}
